#! /bin/bash
if [ $# -ne 1 ]
then
    echo "Usage: release RELEASE_NUMBER"
    exit
fi

RELEASE_NAME="WebGLet-"$1
TARBALL_NAME=$RELEASE_NAME".tar.gz"

# Create release folder
mkdir releases/$RELEASE_NAME

# Do a build
./build
./dist

# Copy webglet to root directory
cp webglet/* releases/$RELEASE_NAME

# Copy libraries in folders
cp -r mootools releases/$RELEASE_NAME
cp -r glmatrix releases/$RELEASE_NAME
cp -r firebugx releases/$RELEASE_NAME
cp -r mixins releases/$RELEASE_NAME
cp -r webgl-debug releases/$RELEASE_NAME

# Copy license
cp LICENSE releases/$RELEASE_NAME

# Copy examples
cp -r ../examples releases/$RELEASE_NAME

# Replace ../../src/webglet with ../..
sed -i "s/\.\.\/\.\.\/src\/webglet/\.\.\/\.\./g" releases/$RELEASE_NAME/examples/*/*.htm
# Replace ../../src with ../..
sed -i "s/\.\.\/\.\.\/src/\.\.\/\.\./g" releases/$RELEASE_NAME/examples/*/*.htm

# Create tarball
cd releases
tar cfz $TARBALL_NAME $RELEASE_NAME

echo "Don't forget to branch and tag the release if it looks good!"
